# -*- coding: utf-8 -*-
"""symmace_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1liXBuMSpMy-eX4xAlpXspiZ679HsyWn0
"""

# ═══════════════════════════════════════════════════════════════
# SymMACE: Symmetry-Aware Multi-Task GNN for Molecular Orbital
# Irreducible Representation Prediction
#
# Reproduces the main result from the paper:
# Train SymMACE on SymQM-3k and evaluate on test set.
#
# Requirements:
#   pip install torch_geometric mace-torch torch_scatter
#               torch_sparse torch_cluster
#
# Data:
#   Download SymQM-3k from https://huggingface.co/datasets/taradutt007/symqm3k/ and place CSVs
#   in the same directory as this script.
# ═══════════════════════════════════════════════════════════════

import os
import json
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.data import Data, Dataset
from torch_geometric.loader import DataLoader
from torch_geometric.nn import global_mean_pool
from torch_cluster import radius_graph
from torch.optim import Adam
from torch.optim.lr_scheduler import ReduceLROnPlateau
from mace.modules import (MACE,
                           RealAgnosticResidualInteractionBlock,
                           RealAgnosticInteractionBlock,
                           gate_dict)
from e3nn import o3

# ── Device ────────────────────────────────────────────────────
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {device}")

# ── 1. LOAD DATA ──────────────────────────────────────────────
DATA_DIR = '.'   # change to your data directory

summary  = pd.read_csv(os.path.join(DATA_DIR, 'target_summary_final.csv'))
atoms_df = pd.read_csv(os.path.join(DATA_DIR, 'atom_details_final.csv'))
orbs_df  = pd.read_csv(os.path.join(DATA_DIR, 'orbital_profile_final.csv'))
splits   = pd.read_csv(os.path.join(DATA_DIR, 'splits.csv'))
summary  = summary.merge(splits, on='qm9_id')

atoms_grouped = atoms_df.groupby('qm9_id')
orbs_grouped  = orbs_df.groupby('qm9_id')

print(f"Molecules: {len(summary)} | "
      f"Train: {(summary['split']=='train').sum()} | "
      f"Val: {(summary['split']=='val').sum()} | "
      f"Test: {(summary['split']=='test').sum()}")

# ── 2. ENCODERS ───────────────────────────────────────────────
ELEMENT_MAP = {'H': 0, 'C': 1, 'N': 2, 'O': 3, 'F': 4}

ALL_IRREPS = sorted(set(
    summary['homo_irrep'].dropna().tolist() +
    summary['lumo_irrep'].dropna().tolist() +
    orbs_df['irrep'].dropna().tolist()
))
IRREP_MAP = {irr: i+1 for i, irr in enumerate(ALL_IRREPS)}
IRREP_MAP['C1_none'] = 0

ALL_PGS = sorted(summary['orca_pg'].unique().tolist())
PG_MAP  = {pg: i for i, pg in enumerate(ALL_PGS)}

NUM_IRREPS = len(IRREP_MAP)   # 20
NUM_PGS    = len(PG_MAP)      # 21

print(f"Irrep vocabulary: {NUM_IRREPS} tokens")
print(f"Point groups    : {NUM_PGS}")

# Valid irreps per point group — derived from actual dataset
# (run scripts/verify_pg_irreps.py to regenerate from raw data)
PG_TO_IRREPS = {
    'C1'   : ['C1_none'],
    'C2'   : ['A', 'B'],
    'C2h'  : ['Ag', 'Au', 'Bg', 'Bu'],
    'C2v'  : ['A1', 'A2', 'B1', 'B2'],
    'C3'   : ['A'],
    'C3h'  : ['Ap', 'App'],
    'C3v'  : ['Ap', 'App'],
    'C4'   : ['A', 'B'],
    'Ci'   : ['Ag', 'Au'],
    'Cs'   : ['Ap', 'App'],
    'D2'   : ['A', 'B1', 'B2', 'B3'],
    'D2d'  : ['A', 'B1', 'B2', 'B3'],
    'D2h'  : ['Ag', 'Au', 'B1g', 'B1u', 'B2g', 'B2u', 'B3g', 'B3u'],
    'D3'   : ['A', 'B'],
    'D3d'  : ['Ag', 'Au', 'Bg', 'Bu'],
    'D3h'  : ['A1', 'A2', 'B1', 'B2'],
    'D6h'  : ['Ag', 'Au', 'B1g', 'B1u', 'B2g', 'B2u', 'B3g', 'B3u'],
    'Dinfh': ['Ag', 'Au', 'B1g', 'B1u', 'B2g', 'B2u', 'B3g', 'B3u'],
    'Oh'   : ['Ag', 'Au', 'B1g', 'B1u', 'B2g', 'B2u', 'B3g', 'B3u'],
    'S4'   : ['A', 'B'],
    'Td'   : ['A', 'B1', 'B2', 'B3'],
}

PG_IRREP_MASK = torch.zeros(NUM_PGS, NUM_IRREPS, dtype=torch.bool)
for pg, valid_irreps in PG_TO_IRREPS.items():
    pg_i = PG_MAP[pg]
    for irr in valid_irreps:
        if irr in IRREP_MAP:
            PG_IRREP_MASK[pg_i, IRREP_MAP[irr]] = True
PG_IRREP_MASK[:, 0] = True   # C1_none always valid
PG_IRREP_MASK = PG_IRREP_MASK.to(device)

# ── 3. DATASET ────────────────────────────────────────────────
class SymQMDataset(Dataset):
    """
    Each molecule becomes a PyG Data object with:
      x          : node features [N, 6] — element one-hot + Mulliken charge
      pos        : 3D coordinates [N, 3]
      edge_index : radius graph at 5Å cutoff
      edge_attr  : interatomic distances [E, 1]
      homo_ev    : HOMO energy in eV
      lumo_ev    : LUMO energy in eV
      homo_irrep : HOMO irrep token (int, 0=C1_none)
      lumo_irrep : LUMO irrep token (int, 0=C1_none)
      homo_irrep_idx : sequential index within irrep channel (-1 if C1)
      lumo_irrep_idx : sequential index within irrep channel (-1 if C1)
      pg_idx     : point group index (int, 0-20)
      has_symmetry : 1 if non-C1, 0 if C1
    """
    def __init__(self, summary_df, atoms_grouped, orbs_grouped,
                 cutoff=5.0):
        super().__init__()
        self.summary       = summary_df.reset_index(drop=True)
        self.atoms_grouped = atoms_grouped
        self.orbs_grouped  = orbs_grouped
        self.cutoff        = cutoff

    def len(self):
        return len(self.summary)

    def get(self, idx):
        row    = self.summary.iloc[idx]
        qm9_id = row['qm9_id']

        # Node features
        mol_atoms   = self.atoms_grouped.get_group(qm9_id)
        n_atoms     = len(mol_atoms)
        elem_onehot = torch.zeros(n_atoms, len(ELEMENT_MAP))
        for i, elem in enumerate(mol_atoms['element'].values):
            elem_onehot[i, ELEMENT_MAP[elem]] = 1.0
        charges = torch.tensor(
            mol_atoms['charge'].values, dtype=torch.float).unsqueeze(1)
        x   = torch.cat([elem_onehot, charges], dim=1)
        pos = torch.tensor(
            mol_atoms[['x','y','z']].values, dtype=torch.float)

        # Edges
        edge_index   = radius_graph(pos, r=self.cutoff, loop=False)
        row_e, col_e = edge_index
        edge_attr    = (pos[row_e] - pos[col_e]).norm(dim=1, keepdim=True)

        # Targets
        homo_ev = torch.tensor([row['homo_ev']], dtype=torch.float)
        lumo_ev = torch.tensor([row['lumo_ev']], dtype=torch.float)

        homo_irrep = IRREP_MAP.get(row['homo_irrep'], 0) \
                     if pd.notna(row['homo_irrep']) else 0
        lumo_irrep = IRREP_MAP.get(row['lumo_irrep'], 0) \
                     if pd.notna(row['lumo_irrep']) else 0
        homo_irrep_idx = float(row['homo_irrep_idx']) \
                         if pd.notna(row['homo_irrep_idx']) else -1.0
        lumo_irrep_idx = float(row['lumo_irrep_idx']) \
                         if pd.notna(row['lumo_irrep_idx']) else -1.0

        return Data(
            x          = x,
            pos        = pos,
            edge_index = edge_index,
            edge_attr  = edge_attr,
            homo_ev    = homo_ev,
            lumo_ev    = lumo_ev,
            homo_irrep = torch.tensor([homo_irrep], dtype=torch.long),
            lumo_irrep = torch.tensor([lumo_irrep], dtype=torch.long),
            homo_irrep_idx = torch.tensor([homo_irrep_idx],
                                          dtype=torch.float),
            lumo_irrep_idx = torch.tensor([lumo_irrep_idx],
                                          dtype=torch.float),
            pg_idx     = torch.tensor([PG_MAP[row['orca_pg']]],
                                      dtype=torch.long),
            qm9_id     = torch.tensor([qm9_id], dtype=torch.long),
            has_symmetry = torch.tensor(
                [0 if row['orca_pg'] == 'C1' else 1], dtype=torch.long),
        )

# ── 4. DATA LOADERS ───────────────────────────────────────────
train_dataset = SymQMDataset(
    summary[summary['split']=='train'], atoms_grouped, orbs_grouped)
val_dataset   = SymQMDataset(
    summary[summary['split']=='val'],   atoms_grouped, orbs_grouped)
test_dataset  = SymQMDataset(
    summary[summary['split']=='test'],  atoms_grouped, orbs_grouped)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader   = DataLoader(val_dataset,   batch_size=32, shuffle=False)
test_loader  = DataLoader(test_dataset,  batch_size=32, shuffle=False)

# ── 5. HELPER ─────────────────────────────────────────────────
def get_atomic_numbers(batch, device):
    """Convert element one-hot to atomic numbers for MACE input."""
    Z_MAP    = torch.tensor([1, 6, 7, 8, 9]).to(device)
    elem_idx = batch.x[:, :5].argmax(dim=1)
    return Z_MAP[elem_idx]

# ── 6. MODEL ──────────────────────────────────────────────────
class SymMACE(nn.Module):
    """
    SymMACE: Symmetry-aware equivariant GNN for molecular orbital prediction.

    Architecture:
      - MACE backbone: equivariant message passing with spherical harmonics
        up to l=2, producing per-atom scalar features [N, 128]
      - Global mean pooling over atom scalars → graph embedding [B, 128]
      - Point group embedding [B, 16] concatenated → combined [B, 144]
      - Four primary output heads:
          homo_head      : energy regression [B] in eV
          lumo_head      : energy regression [B] in eV
          homo_irrep_head: irrep classification [B, 20]
          lumo_irrep_head: irrep classification [B, 20]
      - Two auxiliary heads (used only during training):
          homo_irrep_idx_head: irrep index regression [B]
          lumo_irrep_idx_head: irrep index regression [B]

    The irrep heads use symmetry-constrained masking: logits for
    irreps impossible for the given point group are set to -inf
    before softmax, enforcing physical validity.

    Training uses asymmetric MTL loss:
      L = L_homo_ev + L_lumo_ev
        + 0.05 * L_homo_irrep + 0.3 * L_lumo_irrep   (cross-entropy)
        + 0.02 * L_irrep_idx                           (MAE, aux only)
    C1 molecules (has_symmetry=0) are masked from irrep losses.
    """
    def __init__(self,
                 hidden_irreps    = "128x0e+128x1o",
                 r_max            = 5.0,
                 num_interactions = 2,
                 num_elements     = 5,
                 num_point_groups = 21,
                 num_irreps       = 20,
                 pg_embed_dim     = 16,
                 scalar_dim       = 128):
        super().__init__()

        self.mace = MACE(
            r_max                 = r_max,
            num_bessel            = 8,
            num_polynomial_cutoff = 5,
            max_ell               = 2,
            interaction_cls       = RealAgnosticResidualInteractionBlock,
            interaction_cls_first = RealAgnosticInteractionBlock,
            num_interactions      = num_interactions,
            num_elements          = num_elements,
            hidden_irreps         = o3.Irreps(hidden_irreps),
            MLP_irreps            = o3.Irreps("16x0e"),
            atomic_energies       = torch.zeros(num_elements),
            avg_num_neighbors     = 20.0,
            atomic_numbers        = [1, 6, 7, 8, 9],
            correlation           = 3,
            gate                  = gate_dict['silu'],
        )

        self.pg_embedding = nn.Embedding(num_point_groups, pg_embed_dim)
        combined_dim      = scalar_dim + pg_embed_dim  # 144

        # Primary heads — used at train and inference
        self.homo_head = nn.Sequential(
            nn.Linear(combined_dim, 64), nn.SiLU(),
            nn.Linear(64, 32),          nn.SiLU(),
            nn.Linear(32, 1))
        self.lumo_head = nn.Sequential(
            nn.Linear(combined_dim, 64), nn.SiLU(),
            nn.Linear(64, 32),          nn.SiLU(),
            nn.Linear(32, 1))
        self.homo_irrep_head = nn.Sequential(
            nn.Linear(combined_dim, 64), nn.SiLU(),
            nn.Linear(64, num_irreps))
        self.lumo_irrep_head = nn.Sequential(
            nn.Linear(combined_dim, 64), nn.SiLU(),
            nn.Linear(64, num_irreps))

        # Auxiliary heads — used only during training
        self.homo_irrep_idx_head = nn.Sequential(
            nn.Linear(combined_dim, 32), nn.SiLU(),
            nn.Linear(32, 1))
        self.lumo_irrep_idx_head = nn.Sequential(
            nn.Linear(combined_dim, 32), nn.SiLU(),
            nn.Linear(32, 1))

    def _z_to_idx(self, z):
        Z_TO_IDX = {1:0, 6:1, 7:2, 8:3, 9:4}
        return torch.tensor([Z_TO_IDX[zi.item()] for zi in z],
                            dtype=torch.long, device=z.device)

    def forward(self, z, pos, batch, pg_idx):
        # Build MACE input
        pos        = pos.requires_grad_(True)
        edge_index = radius_graph(pos, r=5.0, batch=batch, loop=False)
        node_attrs = F.one_hot(
            self._z_to_idx(z), num_classes=5).float()
        n_graphs   = batch.max().item() + 1

        mace_input = {
            'positions'   : pos,
            'node_attrs'  : node_attrs,
            'batch'       : batch,
            'edge_index'  : edge_index,
            'ptr'         : torch.zeros(n_graphs+1,
                            dtype=torch.long, device=pos.device),
            'cell'        : torch.zeros(n_graphs, 3, 3,
                            device=pos.device),
            'shifts'      : torch.zeros(edge_index.shape[1], 3,
                            device=pos.device),
            'unit_shifts' : torch.zeros(edge_index.shape[1], 3,
                            device=pos.device),
        }
        out = self.mace(mace_input, training=self.training,
                        compute_force=False, compute_virials=False,
                        compute_stress=False, compute_hessian=False)

        # Graph embedding
        node_scalars = out['node_feats'][:, :128]
        graph_emb    = global_mean_pool(node_scalars, batch)  # [B, 128]
        pg_emb       = self.pg_embedding(pg_idx.squeeze(-1))  # [B, 16]
        combined     = torch.cat([graph_emb, pg_emb], dim=-1) # [B, 144]

        # Store for auxiliary heads in training loop
        self._combined = combined

        # Primary outputs
        homo_ev           = self.homo_head(combined).squeeze(-1)
        lumo_ev           = self.lumo_head(combined).squeeze(-1)
        homo_irrep_logits = self.homo_irrep_head(combined)
        lumo_irrep_logits = self.lumo_irrep_head(combined)

        # Symmetry-constrained masking
        valid_mask        = PG_IRREP_MASK[pg_idx.squeeze(-1)]
        homo_irrep_logits = homo_irrep_logits.masked_fill(
            ~valid_mask, float('-inf'))
        lumo_irrep_logits = lumo_irrep_logits.masked_fill(
            ~valid_mask, float('-inf'))

        return homo_ev, lumo_ev, homo_irrep_logits, lumo_irrep_logits

# ── 7. TRAINING ───────────────────────────────────────────────
def train(model, train_loader, val_loader,
          epochs            = 150,
          lr                = 1e-3,
          lambda_homo_irrep = 0.05,
          lambda_lumo_irrep = 0.3,
          lambda_idx        = 0.02,
          save_path         = 'symmace_best.pt'):
    """
    Multi-task training with asymmetric irrep supervision.

    Loss = L_homo_ev + L_lumo_ev
         + lambda_homo_irrep * L_homo_irrep
         + lambda_lumo_irrep * L_lumo_irrep
         + lambda_idx        * (L_homo_idx + L_lumo_idx)

    All irrep losses masked for C1 molecules (has_symmetry == 0).
    Irrep index loss additionally masked where irrep_idx == -1.
    """
    optimizer = Adam(model.parameters(), lr=lr)
    scheduler = ReduceLROnPlateau(optimizer, patience=10,
                                   factor=0.5, min_lr=1e-5)
    best_val  = float('inf')

    print(f"Parameters        : "
          f"{sum(p.numel() for p in model.parameters()):,}")
    print(f"Lambda homo irrep : {lambda_homo_irrep}")
    print(f"Lambda lumo irrep : {lambda_lumo_irrep}")
    print(f"Lambda idx        : {lambda_idx}")
    print(f"{'Epoch':>6} {'Train':>8} {'vHOMO':>8} {'vLUMO':>8} "
          f"{'vIrpH':>8} {'vIrpL':>8} {'LR':>10}")
    print("-" * 64)

    for epoch in range(1, epochs + 1):
        model.train()
        total_loss = 0

        for batch in train_loader:
            batch = batch.to(device)
            z     = get_atomic_numbers(batch, device)
            optimizer.zero_grad()

            homo_ev, lumo_ev, homo_irrep_logits, lumo_irrep_logits = \
                model(z, batch.pos, batch.batch, batch.pg_idx)
            combined = model._combined

            # Energy losses — all molecules
            loss_homo_ev = F.l1_loss(homo_ev, batch.homo_ev)
            loss_lumo_ev = F.l1_loss(lumo_ev, batch.lumo_ev)

            # Irrep losses — symmetric molecules only
            loss_homo_irrep = torch.tensor(0.0, device=device)
            loss_lumo_irrep = torch.tensor(0.0, device=device)
            loss_homo_idx   = torch.tensor(0.0, device=device)
            loss_lumo_idx   = torch.tensor(0.0, device=device)

            sym_mask = batch.has_symmetry.bool().squeeze(-1)
            if sym_mask.sum() > 0:
                loss_homo_irrep = F.cross_entropy(
                    homo_irrep_logits[sym_mask],
                    batch.homo_irrep.squeeze(-1)[sym_mask])
                loss_lumo_irrep = F.cross_entropy(
                    lumo_irrep_logits[sym_mask],
                    batch.lumo_irrep.squeeze(-1)[sym_mask])

                # Auxiliary irrep index regression
                homo_idx_pred = model.homo_irrep_idx_head(
                    combined[sym_mask]).squeeze(-1)
                lumo_idx_pred = model.lumo_irrep_idx_head(
                    combined[sym_mask]).squeeze(-1)
                homo_idx_true = batch.homo_irrep_idx.squeeze(-1)[sym_mask]
                lumo_idx_true = batch.lumo_irrep_idx.squeeze(-1)[sym_mask]

                valid_h = homo_idx_true > 0
                valid_l = lumo_idx_true > 0
                if valid_h.sum() > 0:
                    loss_homo_idx = F.l1_loss(
                        homo_idx_pred[valid_h], homo_idx_true[valid_h])
                if valid_l.sum() > 0:
                    loss_lumo_idx = F.l1_loss(
                        lumo_idx_pred[valid_l], lumo_idx_true[valid_l])

            loss = (loss_homo_ev + loss_lumo_ev
                    + lambda_homo_irrep * loss_homo_irrep
                    + lambda_lumo_irrep * loss_lumo_irrep
                    + lambda_idx * (loss_homo_idx + loss_lumo_idx))

            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        train_loss = total_loss / len(train_loader)

        # Validation
        model.eval()
        with torch.no_grad():
            homo_maes, lumo_maes = [], []
            homo_correct = lumo_correct = sym_total = 0

            for batch in val_loader:
                batch = batch.to(device)
                z     = get_atomic_numbers(batch, device)
                homo_ev, lumo_ev, hi_logits, li_logits = \
                    model(z, batch.pos, batch.batch, batch.pg_idx)

                homo_maes.append(
                    (homo_ev - batch.homo_ev).abs().mean().item())
                lumo_maes.append(
                    (lumo_ev - batch.lumo_ev).abs().mean().item())

                sym_mask = batch.has_symmetry.bool().squeeze(-1)
                if sym_mask.sum() > 0:
                    homo_correct += (
                        hi_logits[sym_mask].argmax(-1) ==
                        batch.homo_irrep.squeeze(-1)[sym_mask]
                    ).sum().item()
                    lumo_correct += (
                        li_logits[sym_mask].argmax(-1) ==
                        batch.lumo_irrep.squeeze(-1)[sym_mask]
                    ).sum().item()
                    sym_total += sym_mask.sum().item()

        val_homo     = np.mean(homo_maes)
        val_lumo     = np.mean(lumo_maes)
        val_homo_acc = homo_correct / max(sym_total, 1)
        val_lumo_acc = lumo_correct / max(sym_total, 1)
        val_loss     = val_homo + val_lumo

        scheduler.step(val_loss)
        if val_loss < best_val:
            best_val = val_loss
            torch.save(model.state_dict(), save_path)

        if epoch % 10 == 0:
            lr_now = optimizer.param_groups[0]['lr']
            print(f"{epoch:>6} {train_loss:>8.4f} {val_homo:>8.4f} "
                  f"{val_lumo:>8.4f} {val_homo_acc:>8.3f} "
                  f"{val_lumo_acc:>8.3f} {lr_now:>10.6f}")

    print(f"\nBest val loss: {best_val:.4f}")
    return best_val

# ── 8. EVALUATION ─────────────────────────────────────────────
def transition_allowed(pg, h_irrep, l_irrep):
    """Simplified selection rule: same irrep = allowed transition."""
    if pd.isna(h_irrep) or pd.isna(l_irrep):
        return np.nan
    if pg == 'C1':
        return 1
    return int(h_irrep == l_irrep)

@torch.no_grad()
def evaluate(model, loader, split_name='test'):
    """
    Evaluates model on energy MAE, irrep accuracy,
    irrep index MAE, and transition symmetry accuracy.
    Reports overall metrics and per-point-group breakdown
    for the three largest groups (Cs, C2, C2v).
    """
    model.eval()
    homo_preds, homo_trues       = [], []
    lumo_preds, lumo_trues       = [], []
    homo_irrep_preds             = []
    lumo_irrep_preds             = []
    homo_irrep_trues             = []
    lumo_irrep_trues             = []
    homo_idx_preds, lumo_idx_preds = [], []
    homo_idx_trues, lumo_idx_trues = [], []
    pg_indices, sym_flags        = [], []

    for batch in loader:
        batch = batch.to(device)
        z     = get_atomic_numbers(batch, device)

        homo_ev, lumo_ev, hi_logits, li_logits = \
            model(z, batch.pos, batch.batch, batch.pg_idx)
        combined = model._combined

        homo_preds.append(homo_ev.cpu())
        homo_trues.append(batch.homo_ev.cpu())
        lumo_preds.append(lumo_ev.cpu())
        lumo_trues.append(batch.lumo_ev.cpu())
        homo_irrep_preds.append(hi_logits.argmax(-1).cpu())
        lumo_irrep_preds.append(li_logits.argmax(-1).cpu())
        homo_irrep_trues.append(batch.homo_irrep.squeeze(-1).cpu())
        lumo_irrep_trues.append(batch.lumo_irrep.squeeze(-1).cpu())
        homo_idx_preds.append(
            model.homo_irrep_idx_head(combined).squeeze(-1).cpu())
        lumo_idx_preds.append(
            model.lumo_irrep_idx_head(combined).squeeze(-1).cpu())
        homo_idx_trues.append(batch.homo_irrep_idx.squeeze(-1).cpu())
        lumo_idx_trues.append(batch.lumo_irrep_idx.squeeze(-1).cpu())
        pg_indices.append(batch.pg_idx.squeeze(-1).cpu())
        sym_flags.append(batch.has_symmetry.cpu())

    homo_preds       = torch.cat(homo_preds)
    homo_trues       = torch.cat(homo_trues)
    lumo_preds       = torch.cat(lumo_preds)
    lumo_trues       = torch.cat(lumo_trues)
    homo_irrep_preds = torch.cat(homo_irrep_preds)
    lumo_irrep_preds = torch.cat(lumo_irrep_preds)
    homo_irrep_trues = torch.cat(homo_irrep_trues)
    lumo_irrep_trues = torch.cat(lumo_irrep_trues)
    homo_idx_preds   = torch.cat(homo_idx_preds)
    lumo_idx_preds   = torch.cat(lumo_idx_preds)
    homo_idx_trues   = torch.cat(homo_idx_trues)
    lumo_idx_trues   = torch.cat(lumo_idx_trues)
    pg_indices       = torch.cat(pg_indices)
    sym_flags        = torch.cat(sym_flags).bool()

    # Overall metrics
    homo_mae = (homo_preds - homo_trues).abs().mean().item()
    lumo_mae = (lumo_preds - lumo_trues).abs().mean().item()
    homo_acc = (homo_irrep_preds[sym_flags] ==
                homo_irrep_trues[sym_flags]).float().mean().item()
    lumo_acc = (lumo_irrep_preds[sym_flags] ==
                lumo_irrep_trues[sym_flags]).float().mean().item()

    valid_h  = sym_flags & (homo_idx_trues > 0)
    valid_l  = sym_flags & (lumo_idx_trues > 0)
    homo_idx_mae = (homo_idx_preds[valid_h] -
                    homo_idx_trues[valid_h]).abs().mean().item()
    lumo_idx_mae = (lumo_idx_preds[valid_l] -
                    lumo_idx_trues[valid_l]).abs().mean().item()

    # Transition allowed accuracy
    test_df = summary[summary['split']==split_name].reset_index(drop=True)
    test_df['trans_true'] = test_df.apply(
        lambda r: transition_allowed(
            r['orca_pg'], r['homo_irrep'], r['lumo_irrep']), axis=1)
    true_trans = torch.tensor(
        test_df['trans_true'].fillna(-1).values, dtype=torch.long)
    pred_trans = (homo_irrep_preds == lumo_irrep_preds).long()
    valid_trans = sym_flags & (true_trans != -1)
    trans_acc   = (pred_trans[valid_trans] ==
                   true_trans[valid_trans]).float().mean().item()

    print(f"\n=== SymMACE Results ({split_name} set) ===")
    print(f"HOMO MAE            : {homo_mae:.4f} eV")
    print(f"LUMO MAE            : {lumo_mae:.4f} eV")
    print(f"HOMO Irrep Accuracy : {homo_acc:.3f} ({homo_acc*100:.1f}%)")
    print(f"LUMO Irrep Accuracy : {lumo_acc:.3f} ({lumo_acc*100:.1f}%)")
    print(f"HOMO Irrep Idx MAE  : {homo_idx_mae:.2f} positions")
    print(f"LUMO Irrep Idx MAE  : {lumo_idx_mae:.2f} positions")
    print(f"Transition Acc      : {trans_acc:.3f} ({trans_acc*100:.1f}%)")

    # Per-group breakdown for statistically meaningful groups
    print(f"\n{'PG':>8} {'N':>4} {'HOMO MAE':>10} "
          f"{'LUMO MAE':>10} {'L-Irrep':>10}")
    print("-" * 48)
    test_df['homo_mae_val'] = (homo_preds - homo_trues).abs().numpy()
    test_df['lumo_mae_val'] = (lumo_preds - lumo_trues).abs().numpy()
    test_df['lumo_irrep_correct'] = (
        lumo_irrep_preds == lumo_irrep_trues).numpy()

    for pg in ['Cs', 'C2', 'C2v', 'C1']:
        sub = test_df[test_df['orca_pg'] == pg]
        if len(sub) == 0:
            continue
        h = sub['homo_mae_val'].mean()
        l = sub['lumo_mae_val'].mean()
        li = sub['lumo_irrep_correct'].mean() if pg != 'C1' else float('nan')
        li_str = f"{li*100:.1f}%" if not np.isnan(li) else "  --"
        print(f"{pg:>8} {len(sub):>4} {h:>10.4f} {l:>10.4f} {li_str:>10}")

    return dict(
        homo_mae=homo_mae, lumo_mae=lumo_mae,
        homo_acc=homo_acc, lumo_acc=lumo_acc,
        homo_idx_mae=homo_idx_mae, lumo_idx_mae=lumo_idx_mae,
        trans_acc=trans_acc
    )

# ── 9. RUN ────────────────────────────────────────────────────
if __name__ == '__main__':

    CHECKPOINT = 'symmace_best.pt'

    # ── Phase 1: Train from scratch (150 epochs, lr=1e-3) ─────
    print("Phase 1: Training from scratch")
    model = SymMACE().to(device)
    train(model, train_loader, val_loader,
          epochs            = 150,
          lr                = 1e-3,
          lambda_homo_irrep = 0.05,
          lambda_lumo_irrep = 0.3,
          lambda_idx        = 0.02,
          save_path         = CHECKPOINT)

    # ── Phase 2: Fine-tune from best checkpoint (200 epochs, lr=1e-4)
    print("\nPhase 2: Fine-tuning from best checkpoint")
    model.load_state_dict(torch.load(CHECKPOINT))
    train(model, train_loader, val_loader,
          epochs            = 200,
          lr                = 1e-4,
          lambda_homo_irrep = 0.05,
          lambda_lumo_irrep = 0.3,
          lambda_idx        = 0.02,
          save_path         = CHECKPOINT)

    # ── Evaluation ────────────────────────────────────────────
    print("\nLoading best checkpoint for evaluation...")
    model.load_state_dict(torch.load(CHECKPOINT))
    results = evaluate(model, test_loader, split_name='test')

    # Save results
    with open('results.json', 'w') as f:
        json.dump(results, f, indent=2)
    print("\nResults saved to results.json")